// <auto-generated />
namespace HoangTrungThong_54.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Creatae_table_SanPham : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Creatae_table_SanPham));
        
        string IMigrationMetadata.Id
        {
            get { return "202106060826389_Creatae_table_SanPham"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
